CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
IMAGE_PAD_TOKEN_INDEX = -300
IMAGE_GEN_TOKEN_INDEX=-400
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
DEFAULT_IM_PAD_TOKEN = "<im_pad>"
DEFAULT_ACT_START_TOKEN = "<act_start>"
DEFAULT_ACT_END_TOKEN = "<act_end>"
DEFAULT_GEN_TOKEN = "<gentok>"